name: Sync labels
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          delete-other-labels: true
          config-file: 'https://raw.githubusercontent.com/TavstalDev/TavstalDev/refs/heads/main/.github/labels.yml'
